[package]
name = "tokio-serial"
version = "0.8.0"
authors = ["Zac Berkowitz <zac.berkowitz@gmail.com>"]
description = "A serial port implementation for tokio"
license = "MIT"
homepage = "https://github.com/berkowski/tokio-serial"
repository = "https://github.com/berkowski/tokio-serial"
documentation = "http://docs.rs/tokio-serial"
readme = "README.md"
keywords = ["rs232", "serial", "tokio"]
categories = ["asynchronous", "hardware-support"]

[dependencies]
futures = "0.1"
tokio-io = "0.1"
tokio-reactor = "0.1"
bytes = "0.4"
mio = "0.6"
mio-serial = { git = "https://github.com/xoac/mio-serial", branch = "serialport_rs_2_3_1" }

[dev-dependencies]
tokio = "0.1"
